### ISSUE TITLE
Undefined references to the library

### ISSUE THREAD

**Issue by mariusl** [EagleSoC/EZ-PSoC5_LIB#2]
Hi
I am trying to use the library in the latest PSoC Creator with PSoC5. The compiler cannot find reference to any of the used functions of the library.
I have passed it on to the Cypress team and they seem to not be able to compile successfully either.
![capture](https://cloud.githubusercontent.com/assets/942522/17328963/b00dfd8e-58c0-11e6-8dd3-db2afe8dcacd.PNG)

**Comment by mariusl** [comment]
Here is the project file as it is right now.
[Workspace01.zip](https://github.com/EagleSoC/EZ-PSoC5_LIB/files/397012/Workspace01.zip)

**Comment by aleks44** [comment]
Hello,

Please download the new library version -  EZ-PSoC 5LIB V1.2. Let us know if there are further issues.

**Comment by mariusl** [comment]
Hi
Worked fine. One must just include "-lm" in the linker command line. Thanks a lot I am eager to test the library on my hardware.
